### ISSUE TITLE
V5 is named V4 in the fabric.mod.json file.

### ISSUE THREAD

**Issue by K0-RR** [shedaniel/ClothConfig#109]
![Screenshot from 2021-08-04 21-30-18](https://user-images.githubusercontent.com/43277609/128243337-fff2d83f-8377-4430-aeac-2978381c50c8.png)
https://github.com/shedaniel/cloth-config/blob/v5/fabric/src/main/resources/fabric.mod.json

**Comment by shedaniel** [comment]
Thanks for reporting, fixed in https://github.com/shedaniel/cloth-config/commit/914bc11c681f44c1a2d6dfca999d78a9e15b5194
