### ISSUE TITLE
Mods for Minecraft 1.17.x require additional changes for compatibility

### ISSUE THREAD

**Issue by smmmadden** [shedaniel/ClothConfig#126]
**FYI:** Mostly a reminder than issue since these files are often forgotten to be updated.  There are files to change for 1.17.1 to work.
**mods.toml**, ***mixins*** and **pack.mcmeta** need updating for every major release of Minecraft depending on what is included.
Minecraft 1.17.x - Minimum Java Level Supported: 16.0.1
pack.mcmeta files Pack Format=7 for 1.17.x release, 6 for 1.16 and 5 for 1.15, etc.
Minecraft Vanilla Launcher (new one from Microsoft Store) has loading issues that require additional changes to our mods and modpacks.  Read conversation towards the bottom on Forge Support: https://forums.minecraftforge.net/topic/105079-forge-1171-not-launching/?_fromLogin=1
This describes how to workaround the breaking change Microsoft made with the new Vanilla Minecraft launcher.  I'm posting here as I've looked at this 1.17.x version of the mod and found one or both issues exist.  It wasn't an easy process figuring out why mods were not working properly so I've provided the data so you don't have to waste time trying to figure out why.

**Comment by shedaniel** [comment]
Please stop spamming GitHub repos.

Declaring outdated metadata is not the cause of the issue linked to that forum, your issue is caused by too new Java and the quirks with how Forge bootstraps itself, it has never been about the mods.

**Comment by smmmadden** [comment]
I'm not spamming anything @shedaniel - if you choose not to update the mod, that is entirely up to you.  I've only provided the results of what I see in your mod.  As my first statement starts: FYI which is for your information.  Wasn't opening up a debate on programming practices just providing help on what I've found.
