### ISSUE TITLE
Does this mod not support Fabric Loader 0.12.4?

### ISSUE THREAD

**Issue by Ynaught** [shedaniel/ClothConfig#127]
I keep getting this error when Roughly Enough Items tries to use it despite me being on the newest 1.17 version of cloth config:

![image](https://user-images.githubusercontent.com/32611591/143942944-98d8a5e5-15bd-4336-aab8-88f65f64e812.png)

I've tried the newest version of REI and am slowly working my way down the version list of that mod. But if this isn't a loader issue. . . then something silly is going on here.

**Comment by NebelNidas** [comment]
I suppose this issue can be closed now?
