### ISSUE TITLE
Translatable Enums using AutoConfig?

### ISSUE THREAD

**Issue by thedocruby** [shedaniel/ClothConfig#131]
What syntax would I use to add a translation to the enum values of a dropdown or button when using AutoConfig? looking through the code I can see something about a default name provider and translatables, but I can't seem to figure out how to implement it in practice. Also, since the enum handler annotation isn't even mentioned in the auto config 1u wiki, I don't know where else to look. Any help? Thanks.

**Comment by shedaniel** [comment]
override toString

**Comment by thedocruby** [comment]
Okay, thanks, i just thought there might be a less hacky way to do it.
