### ISSUE TITLE
Cloth config causing error with both fabric "right click harvest" mods that results in crash eventually.

### ISSUE THREAD

**Issue by Zach67** [shedaniel/ClothConfig#143]
As the title says, Cloth config causing error with both fabric "right click harvest" mods that results in crash eventually.

Fabric version: 0.12.12 mc 1.18.1

Modlist: 

- additionaladditions 3.0.1
	- additionalbars 2.2.1
	- adorn 3.1.0+1.18.1
	- advanced_runtime_resource_pack 0.5.4 via enhancedblockentities
	- advancementinfo 1.18-fabric0.43.1-1.3
	- advancementplaques 1.4.3
	- adventurez 1.4.6
	- ae2 10.0.0-beta.3
	- ae2wtlib 10.0.0-beta.3
	- agape_space 0.4.5
	- alloy_forgery 2.0.8+1.18
	- amplified_nether 1.0.1
	- animatica 0.2+1.18
	- antighost 1.18-fabric0.43.1-1.1.4
	- apoli 2.2.2 via origins
	- appleskin mc1.18-2.2.0
	- aqupdgrizzly 1.18-1.2.2
	- architects_palette 1.3
	- architectury 3.4.9
	- attributefix 13.0.3
	- authme 2.2.0
	- autoconfig1u 3.2.2 via capes
	- awesomedungeon 2.0.2
	- awesomedungeon_ocean 1.0.3
	- axolotlitemfix 1.1.3
	- balm-fabric 2.4.0+0
	- basicaiots 1.3.3+1.18.1
	- basicshields 1.2.1-1.18.1
	- bclib 1.2.2
	- bedrockwaters 1.6.0+1.18.1
	- beehivetooltips 1.4.1
	- beenfo 1.18.1-fabric0.45.0-1.3.3
	- betteranimalsplus 1.18.1-11.0.3
	- betterend 1.0.0
	- betterf3 1.2.2
	- bettermounthud 1.1.3
	- betternether 6.0.8
	- betterpingdisplay 1.1.1
	- betterthirdperson 1.6.0
	- bitsandchisels 2.6.4
	- blockshifter 1.4.1+fabric-1.18
	- blockus 2.3.4+1.18.1
	- blue_endless_jankson 1.2.1 via jankson
	- blur 2.4.1
	- bno 1.18-7.0.0-Fabric
	- borderlessmining 1.1.1+1.18
	- bosses_of_mass_destruction 1.3.3-1.18
	- botania 1.18.1-427-FABRIC
	- bountiful 2.0.1
	- bowinfinityfix rv11
	- breakprogress 1.0.1
	- bsvsb 2.0.5
	- buildinggadgets 1.0.8
	- calio 1.4.2 via apoli
	- can-i-mine-this-block 1.1.0
	- capes 1.2.2+1.18
	- capybara 1.0.1
	- cardinal-components-base 4.0.1 via polymorph
	- cardinal-components-block 4.0.1 via botania
	- cardinal-components-entity 4.0.1 via polymorph
	- cardinal-components-item 4.0.1 via polymorph
	- cardinal-components-level 4.0.0 via buildinggadgets
	- cardinal-components-world 4.0.0 via bosses_of_mass_destruction
	- carrier 1.9.0
	- cem 0.7.0
	- chas 1.18-1.8-Fabric
	- chisel 1.4.4
	- citresewn 0.8.2+1.18.1
	- cleancut 1.18-4.0-fabric
	- cleardespawn 1.1.5
	- clickthrough 1.18-fabric0.43.1-0.4
	- clienttweaks 7.0.0
	- cloth-api 3.1.61
	- cloth-armor-api-v1 1.5.47 via modern_industrialization
	- cloth-basic-math 0.6.0 via cloth-api
	- cloth-client-events-v0 3.1.61 via cloth-api
	- cloth-common-events-v1 3.1.61 via cloth-api
	- cloth-config 6.1.50
	- cloth-datagen-api-v1 3.1.61 via cloth-api
	- cloth-scissors-api-v1 3.1.61 via cloth-api
	- cloth-utils-v1 3.1.61 via cloth-api
	- clumps 8.0.4
	- collective-fabric 3.14
	- colormatic 2.4.0+mc.1.18
	- com_electronwill_night-config_core 3.6.3 via computercraft
	- com_electronwill_night-config_toml 3.6.3 via computercraft
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_moandjiezana_toml_toml4j 0.7.2 via deepslatecutting
	- com_typesafe_config 1.4.1 via confabricate
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- comforts 1.0.0-1.18
	- completeconfig 1.3.3
	- compress [v1.5]
	- computercraft 1.99.2-alpha1
	- confabricate 2.2.0-SNAPSHOT+4.1.1 via croptopia
	- conjuring 1.0.18+1.18
	- consistency_plus 0.4.3+1.18
	- continuity 1.0.3+1.18
	- cosmetica 0.3.2 via visuality
	- craftingtweaks 13.0.0
	- creativeonepunch 1.3
	- croptopia 1.8.0
	- crowdin-translate 1.4+1.18 via antighost
	- cullleaves 2.3.2
	- customportalapi 0.0.1-beta47-1.18 via mining_dims
	- dankstorage 1.18.1-3.3
	- dark-enchanting 0.6.3+1.18
	- dcch 1.0
	- deathlog 0.2.4+1.18
	- deepslatecutting 1.3.0
	- detailab 2.6.1+1.18-fabric
	- disenchanter 0.1.4+1.18
	- doublejump 1.0.1+mc1.18
	- dragonloot 1.0.9
	- dripstone_fluid_lib 1.1.1 via milk_plus
	- dual_riders 1.0.5
	- dummmmmmy 1.18-1.5.0
	- dungeons_arise 2.1.49c-fabric
	- dynamicfps 2.0.6
	- earthtojavamobs 1.7.4+1.18
	- easymagic 3.2.1
	- eatinganimationid 1.2
	- effective 1.1
	- eldritch_mobs 1.10.2
	- elytratrinket 3.0.0-1.18.1
	- enchant_giver 1.1.0 via mcdw
	- enchdesc 9.0.7
	- endgoblintraders 1.4.2
	- enhancedblockentities 0.5+1.18
	- enhancedcelestials 2.0.6
	- entityculling 1.3.3
	- equipmentcompare 1.2.9
	- exlineawnings 1.18
	- exlinefurniture 1.18.1
	- experiencebugfix 18
	- extragenerators 1.1.1-BETA+1.18
	- extraorigins 1.18-7
	- fabric 0.46.3+1.18
	- fabric-api-base 0.4.2+d7c144a83a via fabric
	- fabric-api-lookup-api-v1 1.5.2+d7c144a83a via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a83a via fabric
	- fabric-blockrenderlayer-v1 1.1.10+3ac43d953a via fabric
	- fabric-command-api-v1 1.1.7+d7c144a83a via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd3a via fabric
	- fabric-containers-v0 0.1.19+d7c144a83a via fabric
	- fabric-content-registries-v0 0.4.7+d7c144a83a via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d953a via fabric
	- fabric-diagonal-panes 0.6.0
	- fabric-dimensions-v1 2.1.10+a1d9bbf53a via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a83a via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a83a via fabric
	- fabric-events-lifecycle-v0 0.2.8+d7c144a83a via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a83a via fabric
	- fabric-item-api-v1 1.3.1+691a79b53a via fabric
	- fabric-item-groups-v0 0.3.5+3ac43d953a via fabric
	- fabric-key-binding-api-v1 1.0.9+d7c144a83a via fabric
	- fabric-keybindings-v0 0.2.7+b4f4f6cd3a via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-language-scala 1.1.0+scala.2.13.6
	- fabric-lifecycle-events-v1 1.4.12+d7c144a83a via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a83a via fabric
	- fabric-mining-level-api-v1 1.0.5+d7c144a83a via fabric
	- fabric-mining-levels-v0 0.1.10+b4f4f6cd3a via fabric
	- fabric-models-v0 0.3.4+d7c144a83a via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a83a via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd3a via fabric
	- fabric-object-builder-api-v1 1.11.3+d7c144a83a via fabric
	- fabric-object-builders-v0 0.7.11+d7c144a83a via fabric
	- fabric-particles-v1 0.2.10+526dc1ac3a via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via invview
	- fabric-registry-sync-v0 0.9.1+d7c144a83a via fabric
	- fabric-renderer-api-v1 0.4.11+b0b66fc33a via fabric
	- fabric-renderer-indigo 0.4.14+d7c144a83a via fabric
	- fabric-renderer-registries-v1 3.2.9+b4f4f6cd3a via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a83a via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d953a via fabric
	- fabric-rendering-v0 1.1.11+b4f4f6cd3a via fabric
	- fabric-rendering-v1 1.10.5+d7c144a83a via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a83a via fabric
	- fabric-resource-loader-v0 0.4.13+d7c144a83a via fabric
	- fabric-screen-api-v1 1.0.8+d7c144a83a via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a83a via fabric
	- fabric-structure-api-v1 2.1.2+d7c144a83a via fabric
	- fabric-tag-extensions-v0 1.2.7+d7c144a83a via fabric
	- fabric-textures-v0 1.0.10+3ac43d953a via fabric
	- fabric-tool-attribute-api-v1 1.3.7+fb3b57b43a via fabric
	- fabric-transfer-api-v1 1.5.8+d7c144a83a via fabric
	- fabricenchantments 0.6.1
	- fabricloader 0.12.12
	- fabricshieldlib 1.4.5-1.18
	- fabrishot 1.6.0
	- fake-player-api 0.3.0 via indrev
	- fallingleaves 1.8.1+1.18.1
	- farsight 1.18-1.5
	- fastfurnace 1.18-4
	- fastopenlinksandfolders 1.0.1
	- ferritecore 4.0.0
	- fiber 0.23.0-2 via botania
	- fluidtank 18.3.0-fabric
	- flytre-lib-base 1.3.0 via flytre_lib
	- flytre-lib-compat 1.0.0 via flytre_lib
	- flytre-lib-config 1.1.0 via flytre_lib
	- flytre-lib-event 1.0.1 via flytre_lib
	- flytre-lib-gui 1.0.0 via flytre_lib
	- flytre-lib-storage 2.3.2 via flytre_lib
	- flytre_lib 1.4.4
	- forgeconfigapiport 3.1.0
	- friendsandfoes 1.0.2
	- fuelinfo 1.0-SNAPSHOT
	- gbfabrictools 1.3.4+1.18 via beenfo
	- geckolib3 3.0.23
	- genesis 1.18.1-1.0.0
	- glassential 1.3.0
	- go-fish 1.4.1-1.18.1
	- gobber2 2.5.58
	- goblintraders 1.4.1
	- golemsgalore 1.1.1-1.18
	- goosik-config 0.2.0 via visuality
	- graveyard 1.1
	- guild 0.3.6
	- hammermod 1.18
	- harvest_scythes 2.4.0
	- healthoverlay 6.0.1
	- heartbond 1.2.0
	- highlighter 1.1.2
	- hookshot 23.0
	- horseinfo 0.4.1-1.18
	- iceberg 1.0.27
	- iknowwhatimdoing 4.0.0
	- impaled 1.0.2
	- incantationem 1.1.3+1.18.1
	- indium 1.0.2-alpha1+mc1.18
	- indrev 1.13.2-BETA
	- infusion_table 1.0.5
	- inmis 2.4.0-1.18
	- inventoryprofilesnext 1.2.3
	- invview 1.4.8-1.18+
	- io_leangen_geantyref_geantyref 1.3.11 via confabricate
	- iris 1.1.3
	- ironchests 1.5.3
	- ironfurnaces 3.0.0
	- itemborders 1.1.5
	- itemmodelfix 1.0.3+1.18
	- jankson 4.0.0+j1.2.0 via adorn
	- java 17
	- justenoughkeys 0.5.2
	- kambrik 3.0.0
	- kanos_config 0.1.4+1.14.4-1.17.1 via pehkui
	- kibe 1.9.4-BETA+1.18
	- kirin 1.10.0-beta.2 via presencefootsteps
	- krypton 0.1.6
	- kyrptconfig 1.3.4-1.18 via quickshulker
	- lambdabettergrass 1.2.2+1.17
	- lambdynlights 2.1.0+1.17
	- languagereload 1.2
	- lazydfu 0.1.2
	- libblockattributes 0.10.0
	- libblockattributes_core 0.10.0 via indrev
	- libblockattributes_fluids 0.10.0 via indrev
	- libblockattributes_items 0.10.0 via indrev
	- libcd 3.0.3+1.16.3 via adorn
	- libgui 5.2.0+1.18 via dark-enchanting
	- libninepatch 1.1.0 via libgui
	- libraryferret 1.0.2
	- lifts 1.4-BETA+1.18
	- lightoverlay 6.0.4
	- lithium 0.7.7
	- lovely_snails 1.0.3+1.18
	- lumiwool 1.2.2
	- maelstrom_library 1.2.3-1.18-rc3 via bosses_of_mass_destruction
	- magiccombatwands 1.0.1
	- magicfungi 0.6.2-BETA+1.18.1
	- magna 1.7.0-1.18-pre1 via indrev
	- mambience 3.2.0+1.18
	- marketcrates 1.4.1
	- mavm 1.0.7a
	- maybe-more-data 1.0.0-1.18 via deepslatecutting
	- mcda 1.9.0
	- mcdar 1.4.3-1.18
	- mcdw 4.0.2
	- mcf-reap 1.7.0
	- medivalmusic 1.18-1.2
	- megane 6.2.0
	- megane-applied-energistics-2 6.2.0+10.0.0-alpha.1 via megane
	- megane-base 6.2.0 via megane
	- megane-extra-generators 6.2.0+1.1.1-BETA-1.18 via megane
	- megane-fabric-transfer 6.2.0+1.5.4-b4f4f6cda9 via megane
	- megane-industrial-revolution 6.2.0+1.13.1-BETA via megane
	- megane-kibe 6.2.0+1.9.4-BETA-1.18 via megane
	- megane-lib-block-attributes 6.2.0+0.10.0 via megane
	- megane-modern-industrialization 6.2.0+1.0.0-alpha.02 via megane
	- megane-reborn-core 6.2.0+5.1.0-beta.2 via megane
	- megane-runtime 6.2.0 via megane
	- megane-team-reborn-energy 6.2.0+2.0.0-beta1 via megane
	- megane-tech-reborn 6.2.0+5.1.0-beta.2 via megane
	- megane-vanilla 6.2.0+1.18.1 via megane
	- megane-wireless-networks 6.2.0+1.4.0 via megane
	- merchantmarkers 1.1.0
	- midnightlib 0.3.1 via blur
	- milk 0.1.5 via milk_plus
	- milk_plus 2.0.1
	- minecraft 1.18.1
	- minieffects 4.0.0
	- mining_dims 1.2.38
	- mm 2.3 via shulkerboxtooltip
	- mo_glass 1.6.1-MC1.18.1
	- mocolors 1.3.0
	- modern_industrialization 1.0.3
	- modmenu 3.0.1
	- morechathistory 1.1.0
	- morevillagers-fabric 3.1.0-SNAPSHOT
	- mostructures 1.3.0-pre1+1.18
	- multipart_entities 1.1.4-1.18-rc3 via bosses_of_mass_destruction
	- myron 1.6.2+1.18.1 via golemsgalore
	- mythic-mounts 1.18-4.0
	- mythicmetals 0.11.0
	- nears 1.1.2
	- nimble 2.1.0
	- ninjaphenix_container_lib 1.2.10
	- no-telemetry 1.3.0
	- nofade 1.18-2.0.1
	- notenoughcrashes 4.1.3+1.18.1
	- omega-config 1.1.0 via dark-enchanting
	- onsoulfire 1.18-1
	- org_anarres_jcpp 1.4.14 via iris
	- org_codehaus_groovy_groovy 3.0.8 via slight-gui-modifications
	- org_codehaus_groovy_groovy-jsr223 3.0.8 via slight-gui-modifications
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_slf4j_slf4j-api 1.7.12 via iris
	- org_spongepowered_configurate-core 4.1.1 via confabricate
	- org_spongepowered_configurate-extra-dfu4 4.1.1 via confabricate
	- org_spongepowered_configurate-gson 4.1.1 via confabricate
	- org_spongepowered_configurate-hocon 4.1.1 via confabricate
	- origins 1.3.1
	- origins-classes 1.2.4
	- owo 0.3.14+1.18
	- patchouli 1.18.1-63-FABRIC
	- pehkui 3.1.0+1.14.4-1.18.1
	- phonos 0.2+1.18
	- physicsmod 2.6.4
	- pickupnotifier 3.1.0
	- pipe 1.6.0
	- playerabilitylib 1.5.0
	- pling 1.5.0
	- plushies 1.1
	- polymorph 0.0.18-1.18.1
	- prefab 3.0.0
	- presencefootsteps 1.4.0
	- pride 1.1.0+1.17 via lambdynlights
	- publicguiannouncement 3.1.0.3
	- pugh_lib 1.2.13 via gobber2
	- pugh_tools 1.1.16 via gobber2
	- puzzleslib 3.1.3
	- quarrymod 0.5.3
	- quartzelv 2.0.1+1.18
	- quickshulker 1.3.3-1.18
	- rad 1.0.1
	- ratsmischief 1.3.4
	- reach-entity-attributes 2.1.1 via botania
	- reborncore 5.1.0-beta.4
	- recipeconditions 0.4.1 via vanillatweaks
	- redbits 1.11.0
	- redstonebits 1.6.2
	- reeses-sodium-options 1.2.4
	- repurposed_structures 3.2.0+1.18.1
	- resourceful_tools 1.2.29
	- respawnablepets 1.18-1
	- rightclickharvest 1.5.1
	- roughlyenoughitems 7.1.357
	- roughlyenoughresources 2.3.0
	- ruined_equipment 1.4.0
	- satin 1.7.0 via blur
	- sculk_worm 0.1.3
	- seedfix 1.0.0 via amplified_nether
	- sgui 1.0.0-rc6+1.18-pre5 via invview
	- shulkerboxtooltip 3.0.5+1.18
	- shulkerutils 1.0.4-1.18 via quickshulker
	- simplemeasuring 1.0.1
	- skinlayers 1.3.1
	- slight-gui-modifications 2.0.2
	- slimyfloor 1.18-1.2.2
	- smoothboot 1.18-1.7.0
	- soaringstructures2 1.18 - 2.0
	- sodium 0.4.0-alpha5+build.9
	- sodium-extra 0.3.7
	- someforgepatchesported 1.0.2
	- spark 1.7.2
	- spruceui 3.3.2+1.17 via lambdabettergrass
	- stacc 1.2.3 via bitsandchisels
	- staffofbuilding 1.4.1-1.18.1
	- starlight 1.0.0+fabric.d0a3220
	- step-height-entity-attribute 1.0.0 via botania
	- stonecutter_recipe_tags 2.0.0 via consistency_plus
	- stoneholm 1.4.2
	- structurized 1.4.0+1.18 via golemsgalore
	- team_reborn_energy 2.0.0-beta1 via ae2
	- techreborn 5.1.0-beta.4
	- terraform-wood-api-v1 2.0.2 via blockus
	- terralith 2.0.8
	- thonkutil 2.6.0+1.18
	- thonkutil-base 1.4.0+6a7a08aec8 via thonkutil
	- thonkutil-capes-v1 1.2.0+a46c8f89c8 via thonkutil
	- thonkutil-coords-v1 1.0.6+6a7a08aec8 via thonkutil
	- thonkutil-customization 1.0.1+6a7a08aec8 via thonkutil
	- thonkutil-legacy 1.0.7+6fa117f8c8 via thonkutil
	- thonkutil-potions-v0 1.2.5+6a7a08aec8 via thonkutil
	- thonkutil-trades-v1 1.1.5+6a7a08aec8 via thonkutil
	- tinyskeletons 3.1.0
	- toolstats 8.0.1
	- tooltipfix 1.0.4-1.18
	- torchbowmod 1.0
	- totw_additions 1.1.0
	- towers_of_the_wild_reworked 2.1.0
	- tradingpost 3.1.2
	- treeharvester-fabric 4.1
	- trinketofundying 2.0.1-1.18
	- trinkets 3.1.0
	- trinketshulkerboxes 2.0.1-1.18.1
	- twm 0.2
	- upgradedshulkers 1.1.1-1.18
	- vanillatweaks 1.5.53
	- veinmining 0.0.11-1.18
	- villagernames-fabric 3.5
	- visuality 0.4.0
	- visualworkbench 3.1.0
	- voidtotem 1.18.1-1.1.0
	- voidz 1.0.5
	- waystones 2.4.1
	- wi_zoom 1.3-MC1.18.1
	- winged 1.18.1-3.1.0
	- wirelessnetworks 1.4.1
	- wmitaf 2.2.0
	- wthit 4.4.0
	- xaerominimap 21.23.0
	- xaeroworldmap 1.19.0
	- xlpackets 2.1-1.17.1
	- xp_storage 1.4.3+1.18
	- xp_storage_trinkets 0.1+1.18
	- xps 0.3.3.b_for_1.18.x_Fabric
	- yigd 1.2.10
	- yosbr 0.1.1

Error:

[19:23:44] [Server thread/FATAL]: Error executing task on Server
java.lang.RuntimeException: Cannot load class me.shedaniel.clothconfig2.api.AbstractConfigListEntry in environment type SERVER
        at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.17) ~[?:?]
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:282) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:240) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.block.CropBlock.onUse(CropBlock:1052) ~[?:?]
        at net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock:937) ~[?:?]
        at net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager:327) ~[?:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler:1057) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:30) ~[?:?]
        at net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket:8) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:741) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by shedaniel** [comment]
You should report to them

**Comment by Zach67** [comment]
> You should report to them

Are you saying this error is not due to cloth-config mod?

**Comment by Zach67** [comment]
I removed the right click to harvest mod and the error still persists.
