### ISSUE TITLE
Cloth Config API 7.0.72 seen as 7.0.65

### ISSUE THREAD

**Issue by Harras420** [shedaniel/ClothConfig#159]
When I try to use the Cloth Config API 7.0.72 for the DragonLoot mod, it crashes the game on start up and says:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!

A potential solution has been determined:
	 - Replace mod 'Cloth Config v6' (cloth-config) 7.0.65 with mod 'Cloth Config v6' (cloth-config), version 7.0.69 or later.
	 
Unmet dependency listing:
	 - Mod 'DragonLoot' (dragonloot) 1.1.1 requires version 7.0.69 or later of mod 'Cloth Config v6' (cloth-config), but only the wrong version is present: 7.0.65!

**Comment by shedaniel** [comment]
It is likely that you have downloaded the forge version instead

**Comment by Harras420** [comment]
Good day,

How do I download the fabric version then?? Where do I get the link for the
fabric one??

Kinde Regards
