### ISSUE TITLE
Current version (7.0.73) crashes in 1.19.1

### ISSUE THREAD

**Issue by PieKing1215** [shedaniel/ClothConfig#168]
Looks like `net.minecraft.client.gui.chat.NarratorChatListener` became `net.minecraft.client.GameNarrator` in 1.19.1, which is causing NoClassDefFoundError when trying to open a cloth screen.

This is only a problem in 1.19.1 not 1.19, and appears to only crash on Forge for some reason (?).

Cloth Config 7.0.73-forge
Minecraft 1.19.1
Forge 42.0.0
No other mods

**Comment by shedaniel** [comment]
Pushed a new update for 8.x
