### ISSUE TITLE
What is cloth-config2

### ISSUE THREAD

**Issue by ea303030** [shedaniel/ClothConfig#169]
every time i try to play a mod that requires cloth config the error code says cloth-config2, version 8.0.75 Or later. which is the one I have

**Comment by shedaniel** [comment]
Make sure you have the latest fabric loader

**Comment by ea303030** [comment]
i did get the latest fabric loader its still there

**Comment by s0meone247** [comment]
You can't mark this closed without it actually being solved.

**Comment by shedaniel** [comment]
stop bumping on an issue from last september, this is an awful issue, without any logs or sort of that, how do you expect one to solve the issue
