### ISSUE TITLE
Trying to navigate using TAB key in config menu crashes the game

### ISSUE THREAD

**Issue by KabanFriends** [shedaniel/ClothConfig#176]
Cloth Config API version: 8.2.88
Minecraft version: 1.19.2
Mod Loader: Happens on both Forge & Fabric

When you try to navigate through the config GUI using TAB key, the game crashes. Strangely, this crash only happens on config menus created manually using cloth config, not the ones created with auto config.

This bug can easily be reproduced by pressing TAB key a few tiems in the Cloth Config API's example config menu.

**Comment by shedaniel** [comment]
Crash Logs?

**Comment by KabanFriends** [comment]
[crash-2022-10-09_20.10.33-client.txt](https://github.com/shedaniel/cloth-config/files/9741393/crash-2022-10-09_20.10.33-client.txt)

**Comment by haykam821** [comment]
This issue is still present on Minecraft 1.19.3.

**Comment by MattSturgeon** [comment]
This is caused by an implementation detail of the search box widget. Changing focus using `<TAB>` might still work if something is already focused. I'll put together a PR with a fix shortly.
