### ISSUE TITLE
Support for 22w45a?

### ISSUE THREAD

**Issue by ghost** [shedaniel/ClothConfig#178]
Will there ever be support for Minecraft version 22w42a? I am currently trying to reconfigure the config for this version, but so far without success.

**Comment by shedaniel** [comment]
I believe the 1.19.2 version works

**Comment by ghost** [comment]
Yes, after reconfiguring the source code everything works on version 22w42a. I did a fork of my own. Unfortunately, cloth-api for example requires some changes (in events). And reasonable sorting has to be rewritten from scratch.

**Comment by shedaniel** [comment]
No, Cloth Config does not need to be updated to 22w42a, it works as is, there is no need to reconfigure, or to update. You might need to update Mod Menu but that's it.

**Comment by ghost** [comment]
Be ready for update into 22w45a. There is additional changes.

**Comment by shedaniel** [comment]
I update when I update the mod. I don't need someone to tell me to do it.
