### ISSUE TITLE
Crash on string list buttons

### ISSUE THREAD

**Issue by Madis0** [shedaniel/ClothConfig#182]
Cloth Config 9.0.93/Minecraft 1.19.3-pre3

These three buttons crash the game
![Screenshot_20221129_204305](https://user-images.githubusercontent.com/8611110/204618291-0f03d6b8-e5df-4ceb-954a-d618db532da0.png)

https://mclo.gs/ahdawjj

To be fair, it might be just the fact of Cloth Config not being updated for pre3 yet as pre3 changed some sound stuff and this crash is about sound... :sweat_smile:

**Comment by shedaniel** [comment]
Yeah it got hit with the pre3 changes.
I don’t leave snapshot update issues open, I will close this. Cloth Config will however be updated very soon
