### ISSUE TITLE
Crash after messing around with config and saving

### ISSUE THREAD

**Issue by frqnny** [shedaniel/ClothConfig#2]
1.14.3 version. 
https://pastebin.com/fwicxMSx
Crash happened after I messed around with the configs that Cloth Config had and clicked saved.

**Comment by shedaniel** [comment]
Try again after updating Cloth Config to the latest version?

**Comment by frqnny** [comment]
Wait, I don't have it downloaded. Isn't it supposed to be embedded in the mods that use it themselves?

**Comment by shedaniel** [comment]
Ah right. Which mods config screen were you opening?

**Comment by frqnny** [comment]
I was opening your mod's test config screen, I believe.

**Comment by shedaniel** [comment]
Unable to reproduce

**Comment by frqnny** [comment]
https://pastebin.com/mDmsGqfa
I still have the crash. I just clicked the boolean variable and it crashed on the Cloth Config configurations.

**Comment by shedaniel** [comment]
Trying to reproduce.

**Comment by shedaniel** [comment]
Nope still unable to reproduce

**Comment by frqnny** [comment]
weird, I'm just gonna close the issue until I can find why it's doing it on mine.
