### ISSUE TITLE
[1.20] Mod doesn't load with Forge 47.1.0 or later

### ISSUE THREAD

**Issue by Rensik** [shedaniel/ClothConfig#211]
It says it's looking for a dependency that doesn't exist.

**Comment by rozbrajaczpoziomow** [comment]
It works for me, care to elaborate / send screenshots/logs / ...?

![image](https://github.com/shedaniel/cloth-config/assets/58668179/f2812497-c908-401c-bdc3-6ce3676129a1)

**Comment by Rensik** [comment]
Odd. It wasn't loading. Now it loads with every dependent mod disabled. Interesting... I guess I have some weeding to do.

**Comment by Rensik** [comment]
Update: found the bad mod. Valkyrien Skies was causing the issue. Thank you!

**Comment by WilliamBlaze** [comment]
I actually found that the cloth config api mod crashes MCDoom Neo forge version on my end. Not sure why, it just keeps giving an error and ending processes on the red loading screen, before crashing to desktop with an error 1 code. but nothing in my logs as to why.

So @rozbrajaczpoziomow, what exactly did you do to get MCDoom to work with Cloth fabric API, considering i can have just the based required mods for MCDOOM installed, along with the cloth API - and minecraft just flips me the bird, but once i disable the cloth api - everything's working smoothly an as intended.

So clearly I'm doing something wrong cause you have a working screenshot of the very version of the cloth fabric API i been using and getting this issue with on my end.

Which frankly sucks cause i wanted to be able to use better combat alongside MCDoom, but the one thing stopping that is the cafuffle with Cloth fabric API (which is a requirement for better combat).


And i don't like the idea of using actual fabric loader mods in my forge mod folder unless absolutely necessary, but currently it seems absolutely nessisary as my only working work around to this issue so far has been a long path of a combination of "Forgified Fabric API" + "Sinytra Connector", Cloth Fabric API [[Fabric 1.20(.1)] v11.1.106] , [player-animation-lib-fabric-1.0.2-rc1+1.20.jar], and [bettercombat-fabric-1.7.3+1.20.1.jar] Just to be able to do so without cause crashing prior to reaching the game menu screen.

But ya know, i would kinda perfer to use the forge version of better combat if possible - but with Cloth Fabric API for forge 1.20.1 being the only thing throwing a monkey wrench in the works here that's preventing me from doing so. And i mean.. i don't think its a ram issue causing my hiccups when i'm giving 9 GBs out of 16gbs of ram to minecraft to use. But i'm no expert here.
