### ISSUE TITLE
[Wiki] ModMenu refered to as Cloth Config.

### ISSUE THREAD

**Issue by Cynosphere** [shedaniel/ClothConfig#23]
On the [ModMenu integration page](https://github.com/shedaniel/ClothConfig/wiki/ModMenu-integration) ModMenu is referred to as Cloth Config.

> Replace ABC with the version of Cloth Config desired, the versions of Cloth Config can be found at CurseForge or Maven.

The links are correct though.

**Comment by shedaniel** [comment]
Thanks! Resolved.
