### ISSUE TITLE
[Question] Version I should use when loading Fabric mods via Sinytra?

### ISSUE THREAD

**Issue by ehx-v1** [shedaniel/ClothConfig#230]
There is a mod called Sinytra Connector that allows to load Fabric mods in a Forge environment (I think there's some transformation stuff involved at runtime). This is a library that has both Forge and Fabric releases. When loading a Fabric mod that depends on this via Sinytra Connector, is it better to use the Forge release as that's the native system, or the Fabric release as that's the same system the dependent mod uses?

**Comment by shedaniel** [comment]
I don't know, it is not officially supported by me, if it works it works.
