### ISSUE TITLE
How can I tell if Cloth Config is working properly, doesn't show on ingame mods list

### ISSUE THREAD

**Issue by natbrazil** [shedaniel/ClothConfig#232]
How can I tell if Cloth Config is working properly, doesn't show on in-game mods list
Running 1.20.2 Win 11 PC Java with Fabric, Iris, Sodium and your mod

Any suggestions? Thanks for you work and any responses.

**Comment by Sjouwer** [comment]
Cloth Config is a library, you'll have to enable this filter to see see libraries in Mod Menu:

![image](https://github.com/shedaniel/cloth-config/assets/84018133/3fcc0142-7681-4aaf-abfa-7067d0e73d2f)
