### ISSUE TITLE
Configs Cannot Save/Update On Fabric Loader 0.15.0/0.15.1

### ISSUE THREAD

**Issue by AViewFromTheTop** [shedaniel/ClothConfig#233]
Originally reported as https://github.com/FabricMC/fabric-loader/issues/865, contains outdated info.
0.15.0 did fix the EnvironmentType annotation for fields, so I'm suspecting this may have to do with it- though, I recommend you do your own testing.
However, on 1.20.2, Cloth Config does not work AT ALL. Regardless if you're in Singleplayer or the Main Menu, NO options will save. It's very frustrating.
I tested Cloth's example config just to be sure it wasn't our issue, and it 100% seems to be a Cloth issue.

**Comment by AViewFromTheTop** [comment]
Update: This seems to persist even when outside of Singleplayer oddly enough.
@Treetrain1 mentioning you here in case it's something to do with FrozenLib.
-Works with SCP 1.15.4 and FrozenLib 1.14.4 on Fabric Loader 14.25
-Doesn't work at all with those mods on Fabric Loader 0.15, continues to revert to the same value no matter what.
Our config syncing seems to actually solve the issue at least when outside Singleplayer which I find very odd.

**Comment by AViewFromTheTop** [comment]
![IMG_2783](https://github.com/shedaniel/cloth-config/assets/87103914/12d13b4d-9925-4081-8925-383148b55b89)
Somehow save consumers are broken on 0.15.0.

**Comment by AViewFromTheTop** [comment]
Doesn't work with Fabric Loader 0.15.1 either.

**Comment by shedaniel** [comment]
I don't get it, seems improbable. Can you provide more details (e.g. logs), or debug this?

**Comment by AViewFromTheTop** [comment]
> I don't get it, seems improbable. Can you provide more details (e.g. logs), or debug this?

I just did a final bit of digging and realized this was actually our issue- I'd completely misunderstood the demo config.
I'm sorry to waste your time, but at least I know where the *actual* issue is- onto an issue report for FrozenLib!
