### ISSUE TITLE
Ask for your permission

### ISSUE THREAD

**Issue by DSLZL** [shedaniel/ClothConfig#238]
Hello, cloth-config makers. I'm DSLZL, and I'm sorry for opening a new issue on your project that is completely unrelated, but I can only contact you on GitHub in China. I'd like to ask if I can put this cloth-config you made into my modpack and publish it in modrinth, because I don't know much about licenses, so I'm here to ask your opinions, and if my actions violate your rights, I'm very sorry and delete the modpack and apologize as soon as I see your reply.
The modpack link in modrinth is: [only-optimized](https://modrinth.com/modpack/only-optimized), if you don't see it, it's because it's still under review
Sorry to interrupt you, but please forgive me for any inconvenience I may have if I do not obtain your permission.
(This passage is supported by Microsoft Translator, if you agree with my behavior, please do not delete this issue, so that I can provide evidence if I need it)
Thank you so much

**Comment by rozbrajaczpoziomow** [comment]
You can contact shedaniel in china on/with https://kook.top/O8RTWY I'm pretty sure.

**Comment by shedaniel** [comment]
The Kook link is no longer a thing since Kook had blocked IPs outside of China.

**Comment by shedaniel** [comment]
Reference the answer from https://github.com/architectury/architectury-api/issues/466#issuecomment-1869281871

**Comment by DSLZL** [comment]
Thank you very much
