### ISSUE TITLE
Forge 1.19.2 Crash

### ISSUE THREAD

**Issue by Leawind** [shedaniel/ClothConfig#240]
When opening config screen, game crash when invoking ConfigBuilder.create()

It says `java.lang.NoSuchMethodError: 'net.minecraft.network.chat.MutableComponent net.minecraft.network.chat.Component.m_237115_(java.lang.String)'`

### Crash report
[crash-2024-01-12_15.16.42-client.txt](https://pastebin.com/8MLtEkHE)

### Reproduce
1. checkout https://github.com/LEAWIND/Third-Person/tree/5703a149e8be3f49b05b09aef1b06a10801012d4
1. run `gradlew forge:runClient`
1. open config screen of mod `leawind_third_person`
1. crash

**Comment by LEAWIND** [comment]
_I'm an idiot_ ಥ_ಥ
