### ISSUE TITLE
DropDown menu don't display list

### ISSUE THREAD

**Issue by Bulldog83** [shedaniel/ClothConfig#27]
Hello.
I've tried to make DropDown menu. But it shows "No suggestions" instead of list with variants.
My code:
```
mapAppearance.addEntry(entryBuilder.startDropdownMenu(lang("current_skin"), MapSkin.getCurrentSkin(), MapSkin::getSkinByName, MapSkin::getName)
.setDefaultValue(MapSkin.getSkin((int) JustMap.CONFIG.getDefault("current_skin")))
.setSelections(MapSkin.getSkins())
.build());
```
MapSkin.getSkins() returns not empty List, I've checked.
And menu in your config shows only one element, but in the Enum in ClothConfig are several of them.
![2020-02-23_21 09 51](https://user-images.githubusercontent.com/20737750/75117250-deae7800-5680-11ea-8234-9148d9f8261b.png)

**Comment by shedaniel** [comment]
oh that list is basically a suggestion of the "search" you typed currently, to display all, you must clear the text field.

**Comment by Bulldog83** [comment]
Ou. Now it's clear..

**Comment by Bulldog83** [comment]
And I've found a bug in the mine code.. :)

**Comment by shedaniel** [comment]
No worries, don't hesitate to ask if you have any other questions. I will close this issue now.
