### ISSUE TITLE
How to add configuration screen for NeoForge 1.21.1+ ?

### ISSUE THREAD

**Issue by NiTiSon** [shedaniel/ClothConfig#293]
Documentation only shows way to integrate config screen for Fabric/ModMenu

**Comment by MattSturgeon** [comment]
You can refer to the "demo" in the newer branches that have neoforge support.

E.g. on the v17 branch which targets 1.21.4
- [neoforge/src/main/.../ClothConfigForge.java](https://github.com/shedaniel/cloth-config/blob/v17/neoforge/src/main/java/me/shedaniel/clothconfig/ClothConfigForge.java)
- [neoforge/src/main/.../ClothConfigForgeDemo.java](https://github.com/shedaniel/cloth-config/blob/v17/neoforge/src/main/java/me/shedaniel/clothconfig/ClothConfigForgeDemo.java)

**Comment by NiTiSon** [comment]
Yeah, this working, thanks
