### ISSUE TITLE
Please update ModMenu

### ISSUE THREAD

**Issue by Ansraer** [shedaniel/ClothConfig#4]
Could you please update mod menu? The version that comes bundled with Cloth is outdated. Prospector recently changed the group id of ModMenu and having the same mod (comes bundled with another mod I depend on) with different group ids has caused quite a few strange problems with my local dev environment. I managed to work around it by manually editing the gradle cache and removing one of them, but that's not really a permanent solution.

**Comment by shedaniel** [comment]
It is done
