### ISSUE TITLE
Crash with latest API version

### ISSUE THREAD

**Issue by Bulldog83** [shedaniel/ClothConfig#41]
Hello. As I undestand, game crashes when API try to show an error, if value, entered to a field, is wrong.

Minecraft: 20w17a
Cloth Config: 4.0.2-unstable

Crash report:
https://gist.github.com/Bulldog83/e27a6cb5c025e0467aa84867fce9d22f

**Comment by Siphalor** [comment]
Came here for the same issue.
The specific issue is in [this line](https://github.com/shedaniel/ClothConfig/blob/03c5066b93f49505d02b3bfed88e0323e27b448b/src/main/java/me/shedaniel/clothconfig2/gui/ClothConfigScreen.java#L419) as you cast an `Optional<Text>` to an `Optional<String>`
