### ISSUE TITLE
Default category option does not seem to work

### ISSUE THREAD

**Issue by Pyrofab** [shedaniel/ClothConfig#42]
`ClothConfigScreen` has a `setFallbackCategory` method, supposedly to change the default category displayed when opening the screen. However, [the code for that feature](https://github.com/shedaniel/ClothConfig/blob/v2/src/main/java/me/shedaniel/clothconfig2/gui/ClothConfigScreen.java#L99-L106) is in the constructor, not in the setter. Am I missing something ?

**Comment by shedaniel** [comment]
Can confirm that this doesn't work.

**Comment by shedaniel** [comment]
Fixed in v2.13.4 that will be out in a few minutes.
