### ISSUE TITLE
Suggestion: True Dropdowns

### ISSUE THREAD

**Issue by Pyrofab** [shedaniel/ClothConfig#43]
Currently, "dropdown menus" behave as text fields with suggestions. This is suboptimal for short sets of possible values like common enums, as users have to erase the existing value to see the possibilities instead of seeing them from a single click.

An alternative to current dropdown menus with no text input and where every possibility is always shown would probably be better than both cycling buttons and text input with suggestions.

A secondary suggestion helping with the above problem is to allow right clicking a text field to erase its current content.

**Comment by shedaniel** [comment]
I feel like I _may_ can add a toggle to turn off filtering the "suggestions" and a toggle to turn off editing the text field.
