### ISSUE TITLE
configuration GUI partial buttons

### ISSUE THREAD

**Issue by nnym** [shedaniel/ClothConfig#46]
I have a 2560x1440 pixel display. When Minecraft is in fullscreen, every configuration menu button looks like 2 separate buttons. Shrinking to a width of c. 2500 pixels connects the "buttons".

**Comment by ejektaflex** [comment]
This happens for me as well, but only on GUI Scale 1 or GUI Scale 2.

![image](https://user-images.githubusercontent.com/23628421/82160510-83dd8480-985b-11ea-8079-8d61372aae0e.png)
![image](https://user-images.githubusercontent.com/23628421/82160523-98ba1800-985b-11ea-9405-0bc647d576c4.png)

When playing on GUI Scale 3+, it looks fine. It's still a bug, but that's a temporary fix :^)
