### ISSUE TITLE
ModifierKeyCode only recognizes 3 mouse key codes

### ISSUE THREAD

**Issue by ejektaflex** [shedaniel/ClothConfig#47]
I'm managing keybinds with ClothConfig for a couple of reasons (no clashes with vanilla keybinds and modifiers are required), and it seems that `ModifierKeyCode::matchesCurrentMouse` will only return true if the mouse key pressed was left, right or middle click on the mouse. Because of this, I wouldn't have the option of assigning a keybind to my mouse's button 4 or button 5 if I tried. GLFW has mouse keys going from 1-8, and they work in vanilla Minecraft as normal keybinds so this should be possible.

[This](https://github.com/shedaniel/ClothConfig/blob/v2/src/main/java/me/shedaniel/clothconfig2/api/ModifierKeyCode.java#L50) is where said code is defined :^)

Note: I'm obviously not setting buttons 4 and 5 as defaults for anything, but they should be options for players to set for themselves nonetheless.

**Comment by shedaniel** [comment]
Should be a bug, might change that piece of code to just get it from GLFW.

**Comment by shedaniel** [comment]
in v2-unstable for 1.16, might backport someday.
