### ISSUE TITLE
Suggestion: Mod Menu Config

### ISSUE THREAD

**Issue by Boobies** [shedaniel/ClothConfig#49]
Hi.

I understand that you are using the configuration menu visible from Mod Menu as a demo for how things should look like. Yet, it's not really elegant for end users to see this stuff just because the mods they're using utilize a library mod; none of the other library mods my mods use do this and it clutters the menu with something that is not really useful. I suggest instead that you instead post screenshots on CurseForge for people to see what they're getting.

Cheers,
Bogdan

**Comment by shedaniel** [comment]
Sorry but I don't think I understand, there are screenshots in the CF page, and a demo in the modmenu, what do you precisely request me to do?

**Comment by Boobies** [comment]
To remove the demo. The mod menu isn't a showcase for developers, it's meant to be a place to configure mods by end users. A more appropriate place for a demo is a separate demo mod that makes use of the library.

**Comment by shedaniel** [comment]
Why? The demo is just there, it doesn't annoy the user.

**Comment by Boobies** [comment]
If it doesn't annoy the user why do you think a user went through the trouble of opening this ticket? If all library mods did this, I'd have to scroll all the way to China to get to the mods for which Mod Menu is actually useful. There is nothing to configure for Cloth Config and no other library mod does this because examples should not be bundled into the final product but rather be distributed separately. How would you like it if every program that uses something like Qt or GTK+ had a pop-up screen showing example widgets when all you wanted to do is use the program?

And I'm not sure what value it's providing that a separate example mod using Cloth Config wouldn't. It's not like developers go "Oh, what did my menus look like? I should consult the demo bundled into my mod."

I literally had to take it out, build it, and rebuild all the mods that use it just to get around this issue.

**Comment by shedaniel** [comment]
You need to click on the example to use the demo though? Do you mean that Cloth Config shouldn't show up in the modmenu or something? That is not related to the demo.

**Comment by Boobies** [comment]
Yes, I mean it shouldn't show up. I presumed the reason why it does is that you want to show off the demo.

**Comment by shedaniel** [comment]
Nope, it is not, I can hide it when the user selects hide library in modmenu (which is the default).

**Comment by Boobies** [comment]
Ah, that sounds good.

**Comment by shedaniel** [comment]
I believe this is fixed.
