### ISSUE TITLE
Add topics to repository for discovery

### ISSUE THREAD

**Issue by MightyKnight** [shedaniel/ClothConfig#55]
Githubs search is really useful if you use topics. To find new libraries, I use `topic:minecraft-fabric topic:library`.
_Using them makes a repository easy to discover and more visible._

You should [add the following topics](https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics) to your repository (these are the most common in fabric projects and fitting for this):
- minecraft
- minecraft-fabric
- fabricmc
- library

E.g.:
![grafik](https://user-images.githubusercontent.com/38622942/89180425-08ee5500-d592-11ea-8ac4-dc68fb8ba155.png)

This is small change that can be done in less than a minute and it would help future users a lot.
Thank you.

P.S. Also do this for AutoConfig propably.

**Comment by shedaniel** [comment]
Added
