### ISSUE TITLE
Question about snapshots

### ISSUE THREAD

**Issue by vico93** [shedaniel/ClothConfig#67]
Hello!

Just to clarify: did you have intentions to update the mod for snapshots as well?

I read some modders in Fabricord which uses cloth as dependency willing to update their mods but cant since it doesn't have a snapshot build. So i went ahead and requested in the requests channel for someone to fork/PR this repo to update for snapshots, but after i felt bad because i didnt ask here before.

Thanks in advance for any answer!

**Comment by shedaniel** [comment]
Cloth Config is released as Public Domain in good faith to allow other people to do whatever to it.

I will not guarantee updates for snapshots, Cloth Config is a gui focused mod and all if not most snapshots break Cloth Config, I simply do not have time to maintain mods on snapshots as my academic pressure starts to build. I will not make snapshots versions of Cloth Config until I see a huge demand of it, the fact that I just got a request for snapshots after 2 weeks from the snapshot that broke it indicates that not enough people want to mod snapshots.

You are free to fork Cloth Config and maintain your own version of Cloth Config given the fact that you change the modid and packages to not conflict with the official Cloth Config when it updates.
