### ISSUE TITLE
Bedrockify causes crash when opening mod settings in modmenu

### ISSUE THREAD

**Issue by Mhowser** [shedaniel/ClothConfig#69]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2020-11-22 20:09:19 PST
Description: Rendering screen

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
    at Not Enough Crashes deobfuscated stack trace.(1.15.1+build.36)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
    at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
    at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
    at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    at me.shedaniel.clothconfig2.api.ScissorsHandler.<clinit>(ScissorsHandler.java:12)
    at me.shedaniel.clothconfig2.gui.widget.DynamicEntryListWidget.method_25394(DynamicEntryListWidget.java:199)
    at me.shedaniel.clothconfig2.gui.widget.DynamicNewSmoothScrollingEntryListWidget.method_25394(DynamicNewSmoothScrollingEntryListWidget.java:136)
    at me.shedaniel.clothconfig2.gui.ClothConfigScreen.method_25394(ClothConfigScreen.java:237)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:616)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.main.Main.main(Main:215)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:567)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in me/shedaniel/clothconfig2/impl/ScissorsHandlerImpl::applyScissors()V has incompatible changes at opcode 112 in callback me/shedaniel/clothconfig2/impl/ScissorsHandlerImpl::applyScissorsOffset.
Expected: [Lme/shedaniel/math/Rectangle;]
   Found: []
    at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
    at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447)
    at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264)
    at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385)
    at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
    at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
    at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
    at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
    ... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Screen render details --
  Screen name: me.shedaniel.clothconfig2.gui.ClothConfigScreen
  Mouse location: Scaled: (944, 57). Absolute: (1888.000000, 114.000000)
  Screen size: Scaled: (960, 500). Absolute: (1920, 1000). Scale factor of 2.000000

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Linux (amd64) version 5.9.0-050900-generic
  Java Version: 13.0.2, AdoptOpenJDK
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
  Memory: 948588368 bytes (904 MB) / 2717908992 bytes (2592 MB) up to 4294967296 bytes (4096 MB)
  CPUs: 4
  JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Cloth Config v4 (cloth-config2), Fabric Loader (fabricloader)
  Fabric Mods: anycapes: AnyCapes 1.0.0
               artifice: Artifice 0.13.1+1.16.2-rc1
               authme: Auth Me 1.4.0
               autoconfig1u: Auto Config v1 Updated 3.2.2
               bedrockify: BedrockIfy 0.2.0
               better_mod_button: Better Mod Button 1.1.4
               carpet: Carpet Mod in Fabric 1.4.12
               chat_heads: Chat Heads 0.1.2+1.16.2
               clientcommands: Client Commands 2.4.7
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.4.5
               cloth-config2: Cloth Config v4 4.8.3
               colormatic: Colormatic 2.2.7+mc.1.16.3
               colorunchained: Color Unchained 1.1.1-1.16.4
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-logging: Cotton Logging 1.0.0-rc.4
               crawl: Crawl 0.8.0
               cullparticles: Cull Particles 1.0
               dynamicfps: Dynamic FPS 1.2.1
               eggtab: Egg Tab 1.1.2+1.15-1.16
               everythingisahat: Everything is a Hat 1.0.3
               fabric: Fabric API 0.26.0+1.16
               fabric-api-base: Fabric API Base 0.2.0+ba858fb83a
               fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
               fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+6a2618f53a
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
               fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
               fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+6a2618f53a
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
               fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+6a2618f53a
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
               fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+6a2618f53a
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+6a2618f53a
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
               fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
               fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+6a2618f53a
               fabric-textures-v0: Fabric Textures (v0) 1.0.5+6a2618f53a
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
               fabricloader: Fabric Loader 0.10.8
               fabrishot: Fabrishot 1.1.0
               fastbench: FastBench 2.3
               fastfurnace: FastFurnace 2.3
               fiber: fiber 0.23.0-2
               jankson: Jankson 3.0.1+j1.2.0
               jumpoverfences: JumpOverFences 1.16-0.0.3
               kirin: Kirin UI 1.7-1.16.2
               lambdacontrols: LambdaControls 1.5.0+1.16.2
               lambdynlights: LambDynamicLights 1.3.2+1.16.4
               libgui: LibGui 3.0.0+1.16.3
               litematica: Litematica 0.0.0-dev.20200913.215807
               lithium: Lithium 0.6.0
               lithium-api: Lithium API 0.6.0
               loadcatcher: Entrypoint Catcher 2.0.0
               malilib: MaLiLib 0.10.0-dev.21+arne.1
               me_shedaniel_cloth_basic-math: basic-math 0.3.0
               minecraft: Minecraft 1.16.4
               minecraftcapes: MinecraftCapes Mod 10
               mm: Manningham Mills 2.1
               modid: Damage Tilt 1.16-fabric-0.1.0
               modmenu: Mod Menu 1.14.6+build.31
               multiconnect: MultiConnect 1.3.34
               multiconnect-api: MultiConnect API 1.3.34
               nbtviewer: NBT Viewer 1.0.0
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               okzoomer: Ok Zoomer 4.0.1+1.16.2
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 20.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
               phosphor: Phosphor 0.6.0+build.7
               raisedclouds: Raised Clouds 1.0.0
               slight-gui-modifications: 'Slight' GUI Modifications 1.4.0
               smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
               sodium: Sodium 0.1.0
               spruceui: SpruceUI 1.6.4
               textbook: Textbook 1.0.0
               voidfog: Void Fog 2.4+1.16.2
               window_title_changer: Window Title Changer 2.1.0-1.16.2
               worldedit: WorldEdit 7.2.0-SNAPSHOT+5436-2226980
               xlpackets: XLPackets 1.1
  Launched Version: fabric-loader-0.10.8-1.16.4
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: Radeon RX 580 Series (POLARIS10, DRM 3.39.0, 5.9.0-050900-generic, LLVM 11.0.0) GL version 4.6 (Compatibility Profile) Mesa 20.3.0-rc2, AMD
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fabric'
  Type: Client (map_client.txt)
  Graphics mode: fancy
  Resource Packs: slightguimodifications:cts_textures, vanilla, file/§l2D Blocks GUI§r (incompatible), file/VanillaTweaks_r722471.zip, fabric/autoconfig1u, fabric/carpet, fabric/chat_heads, fabric/clientcommands (incompatible), fabric/cloth-config2, fabric/cullparticles, fabric/eggtab, fabric/everythingisahat, fabric/fabric, fabric/fabric-api-base, fabric/fabric-biome-api-v1, fabric/fabric-blockrenderlayer-v1, fabric/fabric-containers-v0, fabric/fabric-content-registries-v0, fabric/fabric-crash-report-info-v1, fabric/fabric-events-interaction-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-game-rule-api-v1, fabric/fabric-item-api-v1, fabric/fabric-item-groups-v0, fabric/fabric-key-binding-api-v1, fabric/fabric-keybindings-v0, fabric/fabric-language-kotlin, fabric/fabric-lifecycle-events-v1, fabric/fabric-loot-tables-v1, fabric/fabric-mining-levels-v0, fabric/fabric-models-v0, fabric/fabric-networking-blockentity-v0, fabric/fabric-networking-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-object-builders-v0, fabric/fabric-registry-sync-v0, fabric/fabric-renderer-api-v1, fabric/fabric-renderer-indigo, fabric/fabric-renderer-registries-v1, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-rendering-fluids-v1, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-resource-loader-v0, fabric/fabric-screen-handler-api-v1, fabric/fabric-tag-extensions-v0, fabric/fabric-textures-v0, fabric/fabric-tool-attribute-api-v1, fabric/fabricloader, fabric/fastfurnace, fabric/jankson, fabric/lambdacontrols, fabric/litematica (incompatible), fabric/lithium, fabric/malilib (incompatible), fabric/modid, fabric/modmenu, fabric/multiconnect-api, fabric/okzoomer, fabric/spruceui, fabric/voidfog (incompatible), fabric/worldedit (incompatible), file/VanillaTweaks-itemstitching.zip, fabric/artifice, fabric/colormatic, fabric/dynamicfps, fabric/fabrishot, fabric/lambdynlights, fabric/libgui, fabric/minecraftcapes, fabric/mm, fabric/nbtviewer, fabric/notenoughcrashes, fabric/phosphor, fabric/raisedclouds, fabric/slight-gui-modifications, fabric/smoothscrollingeverywhere, fabric/sodium, fabric/textbook, fabric/window_title_changer, fabric/anycapes, fabric/authme, fabric/multiconnect
  Current Language: English (US)
  CPU: 4x AMD Athlon(tm) X4 880K Quad Core Processor
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by shedaniel** [comment]
Update slight gui modifications
