### ISSUE TITLE
[Bug] Crash after entering the credits in Roughly Enough Items' settings 

### ISSUE THREAD

**Issue by zeabdullah** [shedaniel/ClothConfig#73]
The crash happened when I entered Roughly Enough Items (REI) `settings` and then going to the `credits`. The crash happened mid-way through the slide animation.

Here's the pastebin: https://pastebin.com/bPvG5Nja

I also posted the issue on the REI repo.

**Comment by greentea-cup** [comment]
Is this related to cloth config and not only to REI?

**Comment by zeabdullah** [comment]
Maybe it is, maybe it isn't. I don't know so you could be right. I wanted to post this issue here too in case it could be related to cloth config.

**Comment by shedaniel** [comment]
Can you reproduce with latest REI?

**Comment by zeabdullah** [comment]
I remember it happening only once, and it didn't occur again.

I think I wasn't supposed to open this issue now that I think about it...👉👈

**Comment by shedaniel** [comment]
I'll close this, open a new one if it happens again haha
