### ISSUE TITLE
[docs] incorrect code on autoconfig + modmenu snippet

### ISSUE THREAD

**Issue by rmobis** [shedaniel/ClothConfig#74]
On [Generating a Cloth Config Screen](https://shedaniel.gitbook.io/cloth-config/auto-config/generating-a-cloth-config-screen), the following snippet is present:

```java
@Environment(EnvType.CLIENT)
class ModMenuIntegration implements ModMenuApi {

    @Override
    public ConfigScreenFactory<?> getModConfigScreenFactory() {
        return parent -> AutoConfig.getConfigScreen(ModConfig.class, parent);
    }
}
```

However, this produces the error `Bad return type in lambda expression: Supplier<Screen> cannot be converted to Screen`. Adding a `.get()` at the end fixes it. Here is the complete snippet with the added fix:

``` diff
@Environment(EnvType.CLIENT)
class ModMenuIntegration implements ModMenuApi {

    @Override
    public ConfigScreenFactory<?> getModConfigScreenFactory() {
-        return parent -> AutoConfig.getConfigScreen(ModConfig.class, parent);
+        return parent -> AutoConfig.getConfigScreen(ModConfig.class, parent).get();
    }
}
```

PS: not sure if this is the correct place to open an issue; also would've liked to send a PR, but couldn't find the repo for the docs. sorry

**Comment by sleepy-evelyn** [comment]
Was about to post the same issue :P.

**Comment by shedaniel** [comment]
Thanks for reporting.
