### ISSUE TITLE
Don't use cloth-config as the package name

### ISSUE THREAD

**Issue by AfterRebelion** [shedaniel/ClothConfig#77]
As of 4.9, many packages were renamed and moved around
One of those changes was shadowing some code in me.shedaniel.cloth.cloth-config.shadowed
The hyphen '-' character is considered an illegal character for packages, and will break several packages under this domain, like @\Comment
![imagen](https://user-images.githubusercontent.com/559819/107716855-a0b3c500-6cd2-11eb-8fd0-45a5b711935a.png)
(Image from Intellij IDEA)

Some IDEs will complain further about this:
![imagen](https://user-images.githubusercontent.com/559819/107716944-d193fa00-6cd2-11eb-96be-f054fcfd32a2.png)
(image from VScode)

Please follow naming conventions, so this doesn't break:
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by MaxNeedsSnacks** [comment]
Good catch! This is an error introduced by this part of the gradle buildscript, which naively assumes that the group and jar name are both package name compliant (this is the forge buildscript but it applies to fabric as well):

https://github.com/shedaniel/cloth-config/blob/f29cd4a1197fe409196d45d92704836e9ad9fb55/forge/build.gradle#L58-L60

I'll be sure to update and fix this in my fork, however, there are some other issues that come with shadowing these libraries, so we may have to end up separating them into their own projects (which we'll probably just JIJ on fabric) entirely
