### ISSUE TITLE
AutoConfig class has a wrong import name in binary

### ISSUE THREAD

**Issue by UltimateBoomer** [shedaniel/ClothConfig#90]
In the `AutoConfig` binary, the import for class `net.minecraft.client.gui.screen.Screen` is written as `net.minecraft.client.gui.screens.Screen`, which is causing the code to not compile when using the documented way to create the mod config screen (`AutoConfig.getConfigScreen`). However, in the source code the import is written correctly.

![image](https://user-images.githubusercontent.com/19877616/110218711-2c131700-7e89-11eb-84b9-134251f0d7c8.png)

![image](https://user-images.githubusercontent.com/19877616/110218599-99727800-7e88-11eb-895a-d54f43d22537.png)

![image](https://user-images.githubusercontent.com/19877616/110218558-5dd7ae00-7e88-11eb-8857-9ed98a3d0bee.png)

Affects latest versions (4.11.14), older versions (4.9.5) do not have this bug.

**Comment by shedaniel** [comment]
It is called mappings, what are you doing, loom is supposed to map the classes
