### ISSUE TITLE
Deprecated ModMenu Stuff 

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [shedaniel/ClothConfig#93]
This is put in logs:

`[main/WARN]: WARNING! Mod cloth-config2 is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

`[main/WARN]: WARNING! Mod cloth-basic-math is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

**Comment by shedaniel** [comment]
No

**Comment by DragonEggBedrockBreaking** [comment]
> No

Can you explain further?
